export const groveAbi = [
  {
    type: "function",
    name: "register",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setSessionKey",
    stateMutability: "nonpayable",
    inputs: [
      { name: "session", type: "address" },
      { name: "expiresAt", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "collect",
    stateMutability: "nonpayable",
    inputs: [{ name: "crystalId", type: "uint8" }],
    outputs: [],
  },
  {
    type: "function",
    name: "registered",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "sessionOf",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "getHandles",
    stateMutability: "view",
    inputs: [{ name: "player", type: "address" }],
    outputs: [
      { name: "dust", type: "bytes32" },
      { name: "pot", type: "bytes32" },
      { name: "maps", type: "bytes32" },
      { name: "xpH", type: "bytes32" },
      { name: "lvl", type: "bytes32" },
      { name: "hpH", type: "bytes32" },
      { name: "atkH", type: "bytes32" },
      { name: "defH", type: "bytes32" },
      { name: "luckH", type: "bytes32" },
      { name: "quest", type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "getCollectedMask",
    stateMutability: "view",
    inputs: [{ name: "player", type: "address" }],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "isCollected",
    stateMutability: "view",
    inputs: [
      { name: "player", type: "address" },
      { name: "crystalId", type: "uint8" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "event",
    name: "CrystalCollected",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "crystalId", type: "uint8", indexed: true },
      { name: "caller", type: "address", indexed: true },
    ],
  },
] as const;
